### ISSUE TITLE
ubuntu 17.04

### ISSUE THREAD

**Issue by tony5** [agonzalezro/gnome3-emblems#12]
on a clean install of Ubuntu 17.04 I cant get it to work.
this only thing I see is in syslog.

org.gnome.Nautilus[1367]:   File "/usr/share/nautilus-python/extensions/emblems.py", line 101, in fill_emblems
org.gnome.Nautilus[1367]:   File "/usr/share/nautilus-python/extensions/emblems.py", line 20, in get_property_pages

I have tried the package from the repo as well as the script from git.

**Comment by tony5** [comment]
it seems there is a package dependency issue.
you at least need gnome-icon-theme installed on the system, not necessarily used as your icon theme.

**Comment by agonzalezro** [comment]
Hi @tony5, to be fair I didn't use this package in a long time but I am glad that you got it working!

If you want to provide a PR fixing the dependency that would be great, but either way, thanks for reporting, it will be helpful for others.
